# Generated by Django 4.1.2 on 2022-10-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=200)),
                ('common_name', models.CharField(default='', max_length=200)),
                ('scientific_name', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
                ('call', models.CharField(default='', max_length=500)),
                ('call_number', models.IntegerField(default=-1)),
                ('call_types', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
