# Generated by Django 4.1.2 on 2022-10-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bird_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='calls',
        ),
    ]
