# Generated by Django 4.1.2 on 2022-11-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
