# Generated by Django 4.1.2 on 2022-10-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bird_calls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='calls',
            new_name='call',
        ),
    ]
