# Generated by Django 4.1.2 on 2022-10-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_calls_bird_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='name',
        ),
        migrations.AddField(
            model_name='bird',
            name='call_types',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bird',
            name='common_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bird',
            name='scientific_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bird',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
