# Generated by Django 4.1.2 on 2022-10-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_bird_name_bird_call_types_bird_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='call',
            field=models.CharField(default='', max_length=500),
        ),
    ]
